# Generated by Django 4.2.10 on 2024-02-18 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecat', models.CharField(max_length=20)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('data_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.IntegerField(blank=True, default=0, null=True)),
                ('summa', models.FloatField(blank=True, default=0.0, null=True)),
                ('data_oplati', models.DateTimeField(blank=True, default='01.01.1900', null=True)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klient',
            },
        ),
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametov', models.CharField(max_length=20)),
                ('tekst', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('kolvo', models.IntegerField(default=0)),
                ('data_izm', models.DateTimeField()),
                ('reshenie_moderator', models.IntegerField(blank=True, choices=[(0, 'на рассмотрении'), (1, 'принято'), (2, 'исправить')], default=0)),
                ('tekst_moderator', models.TextField(null=True)),
                ('data_moderator', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Tovars',
                'verbose_name_plural': 'Tovars',
            },
        ),
        migrations.CreateModel(
            name='TovarsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.images')),
                ('tovars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.tovars')),
            ],
            options={
                'verbose_name': 'TovarsImages',
                'verbose_name_plural': 'TovarsImages',
            },
        ),
        migrations.CreateModel(
            name='TovarsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.category')),
                ('tovars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.tovars')),
            ],
            options={
                'verbose_name': 'TovarsCategory',
                'verbose_name_plural': 'TovarsCategory',
            },
        ),
        migrations.AddField(
            model_name='tovars',
            name='category',
            field=models.ManyToManyField(through='dbapp.TovarsCategory', to='dbapp.category'),
        ),
        migrations.AddField(
            model_name='tovars',
            name='images',
            field=models.ManyToManyField(through='dbapp.TovarsImages', to='dbapp.images'),
        ),
        migrations.CreateModel(
            name='KlientTovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.IntegerField(default=1)),
                ('klientitogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.klient')),
                ('tovars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.tovars')),
            ],
            options={
                'verbose_name': 'KlientTovars',
                'verbose_name_plural': 'KlientTovars',
            },
        ),
        migrations.AddField(
            model_name='klient',
            name='tovars',
            field=models.ManyToManyField(through='dbapp.KlientTovars', to='dbapp.tovars'),
        ),
        migrations.AddField(
            model_name='klient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
