# Generated by Django 4.2.10 on 2024-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klienttovars',
            old_name='klientitogo',
            new_name='klient',
        ),
        migrations.AlterField(
            model_name='klient',
            name='data_oplati',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='kolvo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='klient',
            name='summa',
            field=models.FloatField(default=0.0),
        ),
    ]
