# Generated by Django 4.2.10 on 2024-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_alter_klienttovars_kolvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='data_oplati',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='data_izm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='data_moderator',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='reshenie_moderator',
            field=models.IntegerField(choices=[(0, 'на рассмотрении'), (1, 'принято'), (2, 'исправить')], default=0),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='tekst_moderator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
