# Generated by Django 4.2.10 on 2024-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(unique=True, upload_to='images'),
        ),
    ]
